In [1]:
from bridge_problem import *
import pandas as pd

In [4]:
test_cases = read_test_cases("test_cases_hard.txt")
# prob = BridgeProblem(case)
df, sol = generate_report(test_cases, df_only=False)

Finish (7, (9, 9, 9, 9, 9, 9, 30))
Finish (7, (9, 9, 9, 9, 9, 9, 30))
Finish (7, (9, 9, 9, 9, 9, 9, 30))
Finish (7, (44, 55, 66, 33, 8, 1))
Finish (7, (44, 55, 66, 33, 8, 1))
Finish (7, (44, 55, 66, 33, 8, 1))
Finish (8, (5, 6, 4, 3, 3, 4, 5, 6000))
Finish (8, (5, 6, 4, 3, 3, 4, 5, 6000))
Finish (8, (5, 6, 4, 3, 3, 4, 5, 6000))
Finish (8, (50, 60, 40, 30, 30, 40, 50, 6))
Finish (8, (50, 60, 40, 30, 30, 40, 50, 6))
Finish (8, (50, 60, 40, 30, 30, 40, 50, 6))
Finish (8, (10, 100, 1000, 10000, 1000, 100, 10, 1))
Finish (8, (10, 100, 1000, 10000, 1000, 100, 10, 1))
Finish (8, (10, 100, 1000, 10000, 1000, 100, 10, 1))
Finish (9, (100, 2, 3, 4, 5, 60, 7, 8, 9))
Finish (9, (100, 2, 3, 4, 5, 60, 7, 8, 9))
Finish (9, (100, 2, 3, 4, 5, 60, 7, 8, 9))
Finish (9, (3, 3, 3, 4, 4, 4, 4, 8, 8))
Finish (9, (3, 3, 3, 4, 4, 4, 4, 8, 8))
Finish (9, (3, 3, 3, 4, 4, 4, 4, 8, 8))
Finish (10, (10, 20, 30, 40, 50, 60, 70, 80, 90, 100))
Finish (10, (10, 20, 30, 40, 50, 60, 70, 80, 90, 100))
Finish (10, (10, 20, 30, 40, 50, 60, 70, 80, 90, 100))
Finish (10, (100, 90, 80, 70, 60, 60, 70, 80, 90, 100))
Finish (10, (100, 90, 80, 70, 60, 60, 70, 80, 90, 100))
Finish (10, (100, 90, 80, 70, 60, 60, 70, 80, 90, 100))
Finish (10, (5, 5, 5, 5, 5, 5, 5, 5, 5, 5))
Finish (10, (5, 5, 5, 5, 5, 5, 5, 5, 5, 5))
Finish (10, (5, 5, 5, 5, 5, 5, 5, 5, 5, 5))

In [5]:
df

                                                             UCS        IDS  \
Test Case                           Metric
( 9 9 9 9 9 9 30 )                  Solution Cost            120        120
                                    Search Cost             1757       3772
                                    Space Requirement         62         12
                                    Time (s)           0.0302477   0.021874
( 44 55 66 33 8 1 )                 Solution Cost            152        429
                                    Search Cost              640       1398
                                    Space Requirement         41         10
                                    Time (s)           0.0087124  0.0081336
( 5 6 4 3 3 4 5 6000 )              Solution Cost           6039       6061
                                    Search Cost             4564       9359
                                    Space Requirement        152         14
                                    Time (s)            0.142618   0.054923
( 50 60 40 30 30 40 50 6 )          Solution Cost            336        660
                                    Search Cost             4564       9359
                                    Space Requirement        117         14
                                    Time (s)            0.135447  0.0566967
( 10 100 1000 10000 1000 100 10 1 ) Solution Cost          11164      12280
                                    Search Cost             4564       9359
                                    Space Requirement        182         14
                                    Time (s)             0.15187  0.0546985
( 100 2 3 4 5 60 7 8 9 )            Solution Cost            149       1500
                                    Search Cost            11465      22875
                                    Space Requirement        386         16
                                    Time (s)            0.712796   0.132389
( 3 3 3 4 4 4 4 8 8 )               Solution Cost             52         59
                                    Search Cost            11465      22875
                                    Space Requirement        239         16
                                    Time (s)            0.616218   0.145749
( 10 20 30 40 50 60 70 80 90 100 )  Solution Cost            500        620
                                    Search Cost            28090      51812
                                    Space Requirement        479         18
                                    Time (s)             2.96682   0.303133
( 100 90 80 70 60 60 70 80 90 100 ) Solution Cost           1120       1700
                                    Search Cost            28095      51812
                                    Space Requirement        355         18
                                    Time (s)             2.38427   0.299497
( 5 5 5 5 5 5 5 5 5 5 )             Solution Cost             85         85
                                    Search Cost            28095      51812
                                    Space Requirement        368         18
                                    Time (s)             2.21962   0.298684

                                                              A*
Test Case                           Metric
( 9 9 9 9 9 9 30 )                  Solution Cost            120
                                    Search Cost             1757
                                    Space Requirement         52
                                    Time (s)           0.0325882
( 44 55 66 33 8 1 )                 Solution Cost            152
                                    Search Cost              326
                                    Space Requirement         64
                                    Time (s)           0.0069715
( 5 6 4 3 3 4 5 6000 )              Solution Cost           6039
                                    Search Cost             4504
                                    Space Requirement        127
                                    Time (s)            0.151425
( 50 60 40 30 30 40 50 6 )          Solution Cost            336
                                    Search Cost             4395
                                    Space Requirement        144
                                    Time (s)            0.164263
( 10 100 1000 10000 1000 100 10 1 ) Solution Cost          11164
                                    Search Cost             4458
                                    Space Requirement        145
                                    Time (s)            0.161406
( 100 2 3 4 5 60 7 8 9 )            Solution Cost            153
                                    Search Cost             4411
                                    Space Requirement        643
                                    Time (s)            0.534615
( 3 3 3 4 4 4 4 8 8 )               Solution Cost             52
                                    Search Cost            11232
                                    Space Requirement        320
                                    Time (s)            0.749665
( 10 20 30 40 50 60 70 80 90 100 )  Solution Cost            500
                                    Search Cost            27493
                                    Space Requirement        526
                                    Time (s)             3.42993
( 100 90 80 70 60 60 70 80 90 100 ) Solution Cost           1120
                                    Search Cost            28027
                                    Space Requirement        508
                                    Time (s)             2.98583
( 5 5 5 5 5 5 5 5 5 5 )             Solution Cost             85
                                    Search Cost            28095
                                    Space Requirement        368
                                    Time (s)             2.16017

In [7]:
scatters = {dimension: pd.DataFrame(columns=df.columns) for dimension in ["Solution Cost", "Search Cost", "Space Requirement", "Time (s)"]}
for (test_case, metric), algo in df.iterrows():
    scatters[metric].loc[test_case] = algo

from itertools import count
for val in scatters.values():
    cnt = count()
    val.index = val.index.map(lambda x: f"T{next(cnt)+1}")

In [8]:
import plotly.express as px 
import plotly.graph_objects as go
from plotly.subplots import make_subplots

size = 10
colors = px.colors.qualitative.Pastel[:3]
fig = make_subplots(rows=2, cols=2)
for i, dim in enumerate(scatters.keys()):
    r, c = i%2+1, 1 if i < 2 else 2
    fig.add_traces([
        go.Scatter(x=scatters[dim].index, y=scatters[dim]["UCS"], name=f"UCS", legendgroup=f"UCS", mode="lines+markers", marker=dict(size=size, color=colors[0]), showlegend=i==0),
        go.Scatter(x=scatters[dim].index, y=scatters[dim]["IDS"], name=f"IDS", legendgroup=f"IDS", mode="lines+markers", marker=dict(size=size, color=colors[1]), showlegend=i==0),
        go.Scatter(x=scatters[dim].index, y=scatters[dim]["A*"], name=f"A*", legendgroup=f"A*", mode="lines+markers", marker=dict(size=size, color=colors[2]), showlegend=i==0), 
    ], rows=r, cols=c)
    
    fig.update_xaxes(
        title_text="Test Case",
        row=r,
        col=c
    )
    
    fig.update_yaxes(
        title_text=dim,
        row=r,
        col=c
    )
    
fig.update_layout(
    xaxis_title="Test Case",
#     font= dict(
#         family="Courier New",
#         size=20,
        
#     ),
#     title= "Algorithm Comparison"
#     legend_title="Algorithm"
)
fig.write_html("file.html")

In [ ]:
# import plotly.express as px 
# import plotly.graph_objects as go
# from plotly.subplots import make_subplots

# size = 10
# colors = px.colors.qualitative.Pastel[:3]
# fig = make_subplots(rows=4)
# for i, dim in enumerate(scatters.keys()):
#     fig.add_traces([
#         go.Scatter(x=scatters[dim].index, y=scatters[dim]["UCS"], name=f"UCS", legendgroup=f"UCS", mode="lines+markers", marker=dict(size=size, color=colors[0]), showlegend=i==0),
#         go.Scatter(x=scatters[dim].index, y=scatters[dim]["A*"], name=f"A*", legendgroup=f"A*", mode="lines+markers", marker=dict(size=size, color=colors[2]), showlegend=i==0), 
#     ], rows=i+1, cols=1)
    
# #     fig.update_xaxes(
# #         title_text="Test Case",
# #         rows=i+1,
# #         cols=1
# #     )
    
#     fig.update_yaxes(
#         title_text=dim,
#         row=i+1,
#         col=1
#     )
    
# fig.update_layout(
# #     xaxis_title="Test Case",
# #     font= dict(
# #         family="Courier New",
# #         size=20,
        
# #     ),
# #     title= "Algorithm Comparison"
# #     legend_title="Algorithm"
# )
# fig.write_html("file.html")

In [ ]:
scatters["Search Cost"].index.map(lambda x: f"K={x.count(' ')-1}")

In [10]:
scatters["Search Cost"].index

Index(['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10'], dtype='object')

In [17]:
print(df.to_latex())

\begin{tabular}{lllll}
\toprule
            &                            &        UCS &        IDS &         A* \\
Test Case & Metric &            &            &            \\
\midrule
( 1 2 ) & Solution Cost &          2 &          2 &          2 \\
            & Search Cost &          1 &          3 &          1 \\
            & Space Requirement &          1 &          2 &          1 \\
            & Time (1000 calls, in secs) &   3.82e-05 &   3.49e-05 &   4.71e-05 \\
( 3 2 5 ) & Solution Cost &         10 &         11 &         10 \\
            & Search Cost &         15 &         22 &         14 \\
            & Space Requirement &          4 &          4 &          4 \\
            & Time (1000 calls, in secs) &  0.0001595 &   0.000154 &  0.0001857 \\
( 1 3 2 5 ) & Solution Cost &         12 &         12 &         12 \\
            & Search Cost &         66 &        122 &         63 \\
            & Space Requirement &          9 &          6 &          8 \\
            & Time (1000 calls, in secs) &  0.0004984 &  0.0007511 &  0.0007958 \\
( 1 9 2 1 ) & Solution Cost &         13 &         14 &         13 \\
            & Search Cost &         66 &        122 &         61 \\
            & Space Requirement &          9 &          6 &          9 \\
            & Time (1000 calls, in secs) &  0.0005281 &  0.0008551 &  0.0006944 \\
( 3 3 3 3 ) & Solution Cost &         15 &         15 &         15 \\
            & Search Cost &         66 &        122 &         66 \\
            & Space Requirement &          7 &          6 &          7 \\
            & Time (1000 calls, in secs) &  0.0005001 &  0.0007254 &  0.0008629 \\
\bottomrule
\end{tabular}

In [18]:
for val in sol.values():
    print(val.to_latex())

\begin{tabular}{llllll}
\toprule
{} &      ( 1 2 ) &    ( 3 2 5 ) &  ( 1 3 2 5 ) &  ( 1 9 2 1 ) &  ( 3 3 3 3 ) \\
\midrule
0  &  Move a0, a1 &  Move a0, a1 &  Move a0, a2 &  Move a0, a3 &  Move a0, a2 \\
1  &              &    Return a1 &    Return a0 &    Return a3 &    Return a2 \\
2  &              &  Move a1, a2 &  Move a0, a1 &  Move a1, a2 &  Move a1, a2 \\
3  &              &              &    Return a0 &    Return a0 &    Return a1 \\
4  &              &              &  Move a0, a3 &  Move a0, a3 &  Move a1, a3 \\
5  &              &              &              &              &              \\
6  &              &              &              &              &              \\
7  &              &              &              &              &              \\
8  &              &              &              &              &              \\
9  &              &              &              &              &              \\
10 &              &              &              &              &              \\
11 &              &              &              &              &              \\
12 &              &              &              &              &              \\
13 &              &              &              &              &              \\
14 &              &              &              &              &              \\
15 &              &              &              &              &              \\
16 &              &              &              &              &              \\
17 &              &              &              &              &              \\
18 &              &              &              &              &              \\
19 &              &              &              &              &              \\
\bottomrule
\end{tabular}

\begin{tabular}{llllll}
\toprule
{} &      ( 1 2 ) &    ( 3 2 5 ) &  ( 1 3 2 5 ) &  ( 1 9 2 1 ) &  ( 3 3 3 3 ) \\
\midrule
0  &  Move a0, a1 &  Move a0, a1 &  Move a0, a1 &  Move a0, a1 &  Move a0, a1 \\
1  &              &    Return a0 &    Return a0 &    Return a0 &    Return a0 \\
2  &              &  Move a0, a2 &  Move a0, a2 &  Move a0, a2 &  Move a0, a2 \\
3  &              &              &    Return a0 &    Return a0 &    Return a0 \\
4  &              &              &  Move a0, a3 &  Move a0, a3 &  Move a0, a3 \\
5  &              &              &              &              &              \\
6  &              &              &              &              &              \\
7  &              &              &              &              &              \\
8  &              &              &              &              &              \\
9  &              &              &              &              &              \\
10 &              &              &              &              &              \\
11 &              &              &              &              &              \\
12 &              &              &              &              &              \\
13 &              &              &              &              &              \\
14 &              &              &              &              &              \\
15 &              &              &              &              &              \\
16 &              &              &              &              &              \\
17 &              &              &              &              &              \\
18 &              &              &              &              &              \\
19 &              &              &              &              &              \\
\bottomrule
\end{tabular}

\begin{tabular}{llllll}
\toprule
{} &      ( 1 2 ) &    ( 3 2 5 ) &  ( 1 3 2 5 ) &  ( 1 9 2 1 ) &  ( 3 3 3 3 ) \\
\midrule
0  &  Move a0, a1 &  Move a0, a1 &  Move a0, a2 &  Move a0, a3 &  Move a0, a2 \\
1  &              &    Return a1 &    Return a0 &    Return a0 &    Return a2 \\
2  &              &  Move a1, a2 &  Move a0, a1 &  Move a1, a2 &  Move a1, a2 \\
3  &              &              &    Return a0 &    Return a3 &    Return a1 \\
4  &              &              &  Move a0, a3 &  Move a0, a3 &  Move a1, a3 \\
5  &              &              &              &              &              \\
6  &              &              &              &              &              \\
7  &              &              &              &              &              \\
8  &              &              &              &              &              \\
9  &              &              &              &              &              \\
10 &              &              &              &              &              \\
11 &              &              &              &              &              \\
12 &              &              &              &              &              \\
13 &              &              &              &              &              \\
14 &              &              &              &              &              \\
15 &              &              &              &              &              \\
16 &              &              &              &              &              \\
17 &              &              &              &              &              \\
18 &              &              &              &              &              \\
19 &              &              &              &              &              \\
\bottomrule
\end{tabular}